### ISSUE TITLE
Broken datasets link

### ISSUE THREAD

**Issue by EtienneGof** [Lee-CBG/PiTE#1]
Hello Pite Team!

It seems that the dataset links that you provided (in section Pite Usage / 2. Download training and testing dataset) are broken, can you please update them?

**Comment by pzhang84** [comment]
Hello @EtienneGof, thank you for your interest in our work. We are currently in the process of re-uploading the data, but due to its large size, it may take some time. We will be sure to keep you updated on our progress.

**Comment by pzhang84** [comment]
Hi @EtienneGof,

We've updated the download link in the README file for our embedded data. If you have any questions or need further assistance, please feel free to reach out. Thanks!

**Comment by YanpingLugz** [comment]
> Hi @EtienneGof,
> 
> We've updated the download link in the README file for our embedded data. If you have any questions or need further assistance, please feel free to reach out. Thanks!

Hi @pzhang84 
The download links for the training and testing datasets are no longer working for me. Could you please provide new links?
